In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
#Question 1
from sklearn.datasets import load_digits

In [3]:
digit=load_digits()
x=digit.data
y=digit.target

In [4]:
x.shape,y.shape

((1797L, 64L), (1797L,))

In [5]:
#Question 2
from sklearn.preprocessing import StandardScaler

In [6]:
x = StandardScaler().fit_transform(x)
x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [7]:
#Question 4
from sklearn.decomposition import PCA

In [8]:
pca = PCA(n_components = 8)
pca.fit(x)

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [9]:
principalComponents = pca.fit_transform(x)
principalComponents

array([[ 1.91442487, -0.95463541, -3.94557855, ...,  0.5365605 ,
        -1.41291785,  1.48191701],
       [ 0.58911722,  0.92459786,  3.92508087, ..., -0.68272253,
         1.87012827,  0.53865612],
       [ 1.30206819, -0.31734697,  3.02303739, ...,  0.94778121,
        -1.29689568,  1.14439325],
       ...,
       [ 1.02233459, -0.1474942 ,  2.46950636, ..., -0.02366432,
         0.37580634,  0.61917422],
       [ 1.07574715, -0.38055873, -2.45592842, ..., -0.67691004,
         1.02652896,  0.86840489],
       [-1.25830854, -2.22744108,  0.2817004 , ...,  2.30873364,
        -0.40386428, -0.98278982]])

In [10]:
principalDf = pd.DataFrame(data = principalComponents , columns = ['principal component 1', 'principal component 2','principal component 3',
                                                                  'principal component 4','principal component 5','principal component 6',
                                                                  'principal component 7','principal component 8'])
principalDf
##new x

principal component 1  principal component 2  principal component 3  \
0                  1.914425              -0.954635              -3.945579   
1                  0.589117               0.924598               3.925081   
2                  1.302068              -0.317347               3.023037   
3                 -3.020258              -0.869300              -0.801244   
4                  4.529139              -1.093513               0.973905   
5                 -1.301856              -1.148431              -1.575910   
6                  1.434408              -2.957726               2.831537   
7                  0.614098               5.462271               0.658457   
8                 -1.098886              -0.665345              -0.041024   
9                 -0.538068              -0.777486              -1.569938   
10                 3.378653              -0.495413              -2.280270   
11                 2.063296               2.016863               1.540961   
12                -1.936530              -1.815698               2.801160   
13                -3.257690               2.148809              -1.615406   
14                 5.458431               0.025571               0.182973   
15                -3.877253               2.607114               1.857879   
16                 0.921463              -3.262403               3.401405   
17                 1.415250               1.954351               0.560106   
18                -0.926527               2.253178               1.533801   
19                -2.370825              -2.932259              -0.382103   
20                 2.001876              -1.319528              -2.571218   
21                 1.694843               2.075502               0.886030   
22                -3.113960              -1.059609               2.451545   
23                -1.468824               3.910082              -2.077308   
24                 4.003425              -0.322051               0.588202   
25                -0.376372               0.524990               1.356916   
26                 1.286712              -3.969327               2.543101   
27                 3.842051               3.478630              -1.568541   
28                -0.166700               0.934438               1.259238   
29                -2.014464              -2.376986              -0.709233   
...                     ...                    ...                    ...   
1767               4.958461              -1.159608               0.646335   
1768               1.008871              -3.325672              -0.584455   
1769              -0.542850              -0.493039              -3.139195   
1770              -3.314405               1.510463              -0.819481   
1771               2.128424              -2.822381               3.623622   
1772              -1.814377               1.198344              -3.114165   
1773               1.374698              -4.417876               0.544380   
1774               0.762548               0.643751               3.118099   
1775              -0.433613               3.216663               2.011231   
1776              -0.526157              -1.154480              -1.890531   
1777               5.106725              -0.289138               0.342293   
1778               5.899670              -1.709346               1.859456   
1779               1.597040               4.676839               0.469964   
1780              -5.137159              -0.191728               2.223280   
1781              -1.416550              -1.031536               1.195077   
1782              -4.272412              -1.356447               3.059656   
1783              -3.135948              -1.412492               2.238572   
1784               1.568435              -0.438564              -1.840815   
1785               0.057813               1.978381               1.807247   
1786              -0.711466               0.253258              -2.935560   
17

In [11]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444414, 0.06498388, 0.04860022,
       0.04213418, 0.03940701, 0.03384707])

In [12]:
#Question 3
principalDf_train,principalDf_test,y_train,y_test = train_test_split(principalDf,y,test_size = 0.3)

In [13]:
#Question 5
Reg = LogisticRegression()

In [14]:
Reg.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
predict = Reg.predict(principalDf_test)
predict

array([8, 5, 3, 9, 2, 3, 5, 7, 9, 2, 3, 6, 5, 2, 7, 3, 8, 9, 1, 2, 5, 0,
       4, 9, 4, 5, 3, 4, 6, 1, 8, 4, 8, 2, 1, 6, 2, 9, 2, 2, 8, 7, 7, 7,
       0, 7, 7, 6, 7, 9, 1, 3, 0, 5, 0, 4, 2, 5, 1, 9, 1, 3, 5, 9, 7, 6,
       6, 4, 2, 9, 6, 0, 1, 3, 8, 0, 0, 7, 0, 3, 7, 3, 8, 9, 4, 1, 0, 0,
       2, 7, 6, 9, 4, 2, 8, 2, 4, 2, 5, 7, 1, 2, 7, 9, 8, 4, 9, 9, 7, 1,
       5, 3, 6, 8, 8, 9, 8, 8, 4, 7, 7, 0, 2, 8, 1, 1, 7, 0, 7, 7, 1, 3,
       8, 4, 9, 9, 1, 2, 2, 3, 1, 2, 0, 6, 4, 3, 7, 1, 8, 6, 4, 8, 3, 7,
       9, 7, 9, 5, 3, 0, 5, 1, 7, 2, 3, 5, 4, 2, 3, 7, 5, 5, 5, 5, 9, 3,
       0, 0, 2, 0, 8, 7, 0, 9, 4, 0, 0, 3, 1, 8, 1, 8, 7, 4, 0, 1, 5, 0,
       3, 6, 9, 9, 0, 8, 5, 4, 0, 7, 3, 8, 6, 9, 7, 9, 5, 0, 0, 6, 7, 7,
       2, 8, 9, 1, 0, 9, 0, 5, 5, 9, 1, 9, 7, 8, 9, 5, 0, 3, 2, 6, 3, 8,
       6, 9, 2, 2, 1, 4, 5, 6, 6, 5, 4, 9, 7, 3, 1, 7, 5, 3, 5, 5, 8, 2,
       7, 7, 1, 5, 6, 2, 1, 5, 1, 3, 0, 3, 6, 2, 0, 9, 0, 5, 0, 9, 5, 1,
       3, 1, 7, 6, 1, 5, 4, 5, 9, 7, 0, 0, 0, 0, 1,

In [16]:
#Question 6
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [17]:
from sklearn import metrics
metrics.accuracy_score(predict, y_test)

0.8740740740740741

In [18]:
print(confusion_matrix(predict, y_test))

[[59  0  0  0  0  0  0  0  0  1]
 [ 0 44  3  1  0  0  0  0  5  2]
 [ 0  1 47  0  0  0  0  0  2  0]
 [ 0  0  1 44  0  0  0  0  2  7]
 [ 1  1  0  0 49  0  0  0  0  0]
 [ 0  1  0  1  0 53  0  0  3  1]
 [ 0  0  0  0  0  1 53  0  1  0]
 [ 0  0  1  1  1  0  0 48  1  2]
 [ 0  0  1  2  0  1  0  1 31  1]
 [ 0  4  0  8  0  1  0  0  8 44]]


In [19]:
print(classification_report(predict, y_test))

             precision    recall  f1-score   support

          0       0.98      0.98      0.98        60
          1       0.86      0.80      0.83        55
          2       0.89      0.94      0.91        50
          3       0.77      0.81      0.79        54
          4       0.98      0.96      0.97        51
          5       0.95      0.90      0.92        59
          6       1.00      0.96      0.98        55
          7       0.98      0.89      0.93        54
          8       0.58      0.84      0.69        37
          9       0.76      0.68      0.72        65

avg / total       0.88      0.87      0.88       540

