In [1]:
#Question 1 Importing the libraries
from sklearn import model_selection
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
#Importing the dataset
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data")
df

B  1  1.1  1.2  1.3
0    R  1    1    1    2
1    R  1    1    1    3
2    R  1    1    1    4
3    R  1    1    1    5
4    R  1    1    2    1
5    R  1    1    2    2
6    R  1    1    2    3
7    R  1    1    2    4
8    R  1    1    2    5
9    R  1    1    3    1
10   R  1    1    3    2
11   R  1    1    3    3
12   R  1    1    3    4
13   R  1    1    3    5
14   R  1    1    4    1
15   R  1    1    4    2
16   R  1    1    4    3
17   R  1    1    4    4
18   R  1    1    4    5
19   R  1    1    5    1
20   R  1    1    5    2
21   R  1    1    5    3
22   R  1    1    5    4
23   R  1    1    5    5
24   L  1    2    1    1
25   B  1    2    1    2
26   R  1    2    1    3
27   R  1    2    1    4
28   R  1    2    1    5
29   B  1    2    2    1
..  .. ..  ...  ...  ...
594  L  5    4    5    1
595  L  5    4    5    2
596  L  5    4    5    3
597  B  5    4    5    4
598  R  5    4    5    5
599  L  5    5    1    1
600  L  5    5    1    2
601  L  5    5    1    3
602  L  5    5    1    4
603  L  5    5    1    5
604  L  5    5    2    1
605  L  5    5    2    2
606  L  5    5    2    3
607  L  5    5    2    4
608  L  5    5    2    5
609  L  5    5    3    1
610  L  5    5    3    2
611  L  5    5    3    3
612  L  5    5    3    4
613  L  5    5    3    5
614  L  5    5    4    1
615  L  5    5    4    2
616  L  5    5    4    3
617  L  5    5    4    4
618  L  5    5    4    5
619  L  5    5    5    1
620  L  5    5    5    2
621  L  5    5    5    3
622  L  5    5    5    4
623  B  5    5    5    5

[624 rows x 5 columns]

In [3]:
#Printing the head of the dataset
df.head()

B  1  1.1  1.2  1.3
0  R  1    1    1    2
1  R  1    1    1    3
2  R  1    1    1    4
3  R  1    1    1    5
4  R  1    1    2    1

In [4]:
#Printing the shape of the dataset
df.shape

(624, 5)

In [5]:
#Question 2 Slicing the dataset(preparing the data)
X=df.drop(["B"],axis=1)
Y=df["B"]

In [34]:
#Question 3 Split the dataset by using train_test_split().
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)

In [35]:
#Question 4
from sklearn import tree

In [36]:
model=tree.DecisionTreeClassifier(max_leaf_nodes=10)

In [37]:
##The fit method of this class is called to train the algorithm on the training data,
which is passed as parameter to the fit method
model.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=10,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [38]:
pred = model.predict(X_test)

In [39]:
from sklearn import metrics
metrics.accuracy_score(Y_test,pred)

0.776

In [40]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,pred))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        11
          L       0.72      0.89      0.79        54
          R       0.84      0.82      0.83        60

avg / total       0.72      0.78      0.74       125



In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
confusion_matrix(Y_test,pred)

array([[ 0,  8,  3],
       [ 0, 48,  6],
       [ 0, 11, 49]], dtype=int64)

In [43]:
#Question 4(b)
model1=tree.DecisionTreeClassifier(criterion="entropy",max_depth=10)

In [44]:
model1.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [45]:
pred1 = model1.predict(X_test)

In [46]:
metrics.accuracy_score(Y_test,pred1)

0.744

In [47]:
print(classification_report(Y_test,pred1))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        11
          L       0.79      0.78      0.79        54
          R       0.89      0.85      0.87        60

avg / total       0.77      0.74      0.76       125



In [48]:
confusion_matrix(Y_test,pred1)

array([[ 0,  8,  3],
       [ 9, 42,  3],
       [ 6,  3, 51]], dtype=int64)

In [49]:
#Question 5 Loading scikits random forest classifier library
from sklearn.ensemble import RandomForestClassifier

In [50]:
## Create a random forest classifier
model2=RandomForestClassifier(random_state=1,max_depth=10 )

In [51]:
## Train the classifier tp take the training features
model2.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [52]:
pred2 = model2.predict(X_test)

In [53]:
metrics.accuracy_score(Y_test,pred2)

0.824

In [54]:
print(classification_report(Y_test,pred2))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        11
          L       0.85      0.87      0.86        54
          R       0.90      0.93      0.92        60

avg / total       0.80      0.82      0.81       125



In [55]:
confusion_matrix(Y_test,pred2)

array([[ 0,  7,  4],
       [ 5, 47,  2],
       [ 3,  1, 56]], dtype=int64)

In [56]:
##Question 5(b)
model3=RandomForestClassifier(criterion="entropy")

In [57]:
model3.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [58]:
pred3 = model3.predict(X_test)

In [59]:
metrics.accuracy_score(Y_test,pred3)

0.816

In [60]:
print(classification_report(Y_test,pred3))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        11
          L       0.83      0.89      0.86        54
          R       0.96      0.90      0.93        60

avg / total       0.82      0.82      0.82       125



In [61]:
##Create a confusion matrix
confusion_matrix(Y_test,pred3)

array([[ 0,  9,  2],
       [ 6, 48,  0],
       [ 5,  1, 54]], dtype=int64)